[package]
name = "token_mint"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.24.2"
anchor-spl = "0.24.2"
mpl-token-metadata = "1.2.0"
solana-program = "1.9.9" 

[lib]
name = "token_mint"
path = "src/lib.rs"
